# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RED": "02_dashboard_two.ipynb",
         "BLUE": "02_dashboard_two.ipynb",
         "GREEN": "02_dashboard_two.ipynb",
         "BOLD": "02_dashboard_two.ipynb",
         "ITALIC": "02_dashboard_two.ipynb",
         "RESET": "02_dashboard_two.ipynb",
         "dashboard_one": "01_dashboard_one.ipynb",
         "style": "02_dashboard_two.ipynb",
         "dashboard_two": "02_dashboard_two.ipynb",
         "ds_choice": "02_dashboard_two.ipynb",
         "plt_classes": "02_dashboard_two.ipynb",
         "display_images": "02_dashboard_two.ipynb",
         "display_ui": "98_display.ipynb"}

modules = ["core.py",
           "dashboard_one.py",
           "dashboard_two.py",
           "display.py"]

doc_url = "https://asvcode.github.io/visualtemp/"

git_url = "https://github.com/asvcode/visualtemp/tree/master/"

def custom_doc_links(name): return None
