# AUTOGENERATED! DO NOT EDIT! File to edit: 04_datablock.ipynb (unless otherwise specified).

__all__ = ['ds_3']

# Cell
def ds_3():
    """GUI for 3rd Accordion window"""
    db_button = widgets.Button(description='Confirm')
    ds_3.d1 = widgets.ToggleButtons(value=None, options=['PILImage', 'PILImageBW'], description='', button_style='info')
    ds_3.e1 = widgets.ToggleButtons(value=None, options=['CategoryBlock', 'MultiCategoryBlock'], description='', button_style='warning')
    ds_3.g = widgets.ToggleButton(description='parent_label', button_style='danger', value=False)
    ds_3.s = widgets.ToggleButtons(value=None, options=['RandomSplitter', 'GrandparentSplitter'],
                                   description='', button_style='success')
    form_items = [ds_3.d1, ds_3.e1, ds_3.s ,ds_3.g]

    form_t = Layout(display='flex',
                    flex_flow='row',
                    align_items='stretch',
                    border='solid 1px',
                    width='100%')
    form = Box(children=form_items, layout=form_t)
    display(form)
    display(db_button)
    db_out = widgets.Output()
    display(db_out)
    def on_db_click(b):
        with db_out:
            clear_output()
            block_ch()
            code_test()
    db_button.on_click(on_db_click)
