# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"repeat_one": "00_core.ipynb",
         "RED": "05_code.ipynb",
         "BLUE": "05_code.ipynb",
         "GREEN": "05_code.ipynb",
         "BOLD": "05_code.ipynb",
         "ITALIC": "05_code.ipynb",
         "RESET": "05_code.ipynb",
         "dashboard_one": "01_dashboard_one.ipynb",
         "style": "03_augmentation_dashboard.ipynb",
         "dashboard_two": "02_dashboard_two.ipynb",
         "ds_choice": "02_dashboard_two.ipynb",
         "plt_classes": "02_dashboard_two.ipynb",
         "display_images": "02_dashboard_two.ipynb",
         "aug_dash": "03_augmentation_dashboard.ipynb",
         "aug_choice": "03_augmentation_dashboard.ipynb",
         "aug_paras": "03_augmentation_dashboard.ipynb",
         "aug": "03_augmentation_dashboard.ipynb",
         "aug_dash_choice": "03_augmentation_dashboard.ipynb",
         "code_test": "04_datablock.ipynb",
         "stats_info": "03_augmentation_dashboard.ipynb",
         "ds_3": "04_datablock.ipynb",
         "block_ch": "04_datablock.ipynb",
         "write_code": "05_code.ipynb",
         "display_ui": "98_display.ipynb"}

modules = ["core.py",
           "dashboard_one.py",
           "dashboard_two.py",
           "augmentation_dashboard.py",
           "datablock.py",
           "code.py",
           "display.py"]

doc_url = "https://asvcode.github.io/fast_gui/"

git_url = "https://github.com/asvcode/fast_gui/tree/master/"

def custom_doc_links(name): return None
